import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import QrCode from 'react-qr-code';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [link, setLink] = useState('');
  const [showQrCode, setShowQrCode] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Free qr code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Generate your free QR Code, forever
        </h1>

        <input style={{
          height: 32, width: 300, border: '1px solid grey', fontSize: 18, marginTop: 32,
          padding: 8,
          borderRadius: 8,
        }} 
        value={link}
        onChange={(e) => setLink(e.target.value)}
        />

        <button
          style={{
            height: 48,
            width: 300,
            fontSize: 24,
            marginTop: 16,
            color: '#fff',
            background: "#7159c1",
            borderRadius: 12,
            border: 'none',
            cursor: 'pointer',
            marginBottom: 32,
          }}
          onClick={() => setShowQrCode(true)}
          >Submit</button>

          {
            showQrCode && (
              <QrCode value={link} />
            )
          }
      </main>
            <footer className={styles.footer}>
        <a
          href="https://github.com/pedrohjleite"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with 💜 by Pedro Leite
        </a>
      </footer>
    </div>
  )
}

export default Home
